spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  20MB
      max-request-size:  100MB
mybatis-plus:
  typeAliasesPackage: com.ty.dc.entity
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto