dc:
  profile: d:/data
  redirecturl: fd.huhanyi.com
server:
  port: 8081
  servlet:
    context-path: /order
  tomcat:
    uri-encoding: UTF-8
    max-threads: 10
    min-spare-threads: 5
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  20MB
      max-request-size:  100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.116.119.163:3306/dc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: dc
    password: dcgl@123!!!
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  typeAliasesPackage: com.ty.dc.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
wechat:
  cp:
    corpId: wwf0325d82e6544daf
    baseApiUrl: https://cgwework.sz.gov.cn
    appConfigs:
      - agentId: 1000033
        secret: qqiiw0LZ3U_N76fgAkHpI7Wt9PACYH80hJHrxWfG90M
        token: 111
        aesKey: 111